services:
  otter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - budget-data:/data
    environment:
      - APP__DATABASE__URL=sqlite:///data/budget.db
    ports:
      - "3000:3000"

volumes:
  budget-data:
